# Generated by Django 4.0.3 on 2022-03-07 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('send_date_time', models.DateTimeField(auto_now=True)),
                ('send_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_from', to=settings.AUTH_USER_MODEL)),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
