# Generated by Django 4.0.3 on 2022-03-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_propertybookmark_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_of_added',
        ),
    ]
