# Generated by Django 4.0.3 on 2022-03-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_added', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
