# Generated by Django 4.0.3 on 2022-03-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_comments_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
